version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - ./app:/app  # Allows real-time updates without rebuild
    networks:
      - private_network
    depends_on:
      - database  # Ensure database starts before Flask
    environment:
      - PYTHON_ENV=production

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - private_network
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist database data

networks:
  private_network:
    driver: bridge

volumes:
  pgdata:  # Persistent database storage
